name: Build Kernel Zenfone Max Pro M2
on:
  push:
    branches:
      - master
jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
        pacman -Sy --noconfirm git bc inetutils python3 flex bison libc++ libxml2 python-pip zip wget cpio jdk-openjdk tzdata && python3 -m pip install networkx && pip3 install --upgrade gupload
    - name: Clone Source
      run: git clone --single-branch --depth=1 https://github.com/nerdprojectorg/android_kernel_asus_sdm660 msm-4.19
    - name: Build Kernel
      run: bash kernel.sh
