name: Build Kernel Zenfone Max Pro M2
on:
  push:
    branches:
      - master
jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
        pacman -Sy --noconfirm git bc inetutils python3 flex bison libc++ libxml2 python-pip zip wget cpio jdk-openjdk tzdata && python3 -m pip install networkx && pip3 install --upgrade gupload
    - name: Clone Source
      run: |
        git clone --single-branch --depth=1 https://github.com/NerdZ3ns/android_kernel_asus_sdm660 -b topaz msm-4.19
        cd msm-4.19
        git fetch https://github.com/nerdprojectorg/android_kernel_asus_sdm660
        git cherry-pick a06609ffbfe2b2ab8bc852a109d3d67888efa403^..b3339c5d5acc8de1870b108d8011b4f7f5d63827
        git revert ca6614ce49fc47b41c4cdc873e5aa8956a970ec9
    - name: Build Kernel
      run: bash kernel.sh
