name: Build Kernel Zenfone Max Pro M2
on:
  push:
    branches:
      - master
jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: z3zens/ubuntu:latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone Source
      run: git clone --single-branch --depth=1 https://github.com/NerdZ3ns/android_kernel_asus_sdm660 -b tm-rebase msm-4.4
    - name: Build Kernel
      run: bash kernel.sh
